# Site settings
title: My Blog
email: hanakim@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
phone: "9320485"
url: "http://yourdomain.com"
paginate: 3

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['README.md']
